### PR TITLE
Added deprecation warnings and fixed #2

### LINKED ISSUE #2: The Printer throws an exception when serializing `Json` to `String`
The Printer throws an exception when serializing `Json` to `String`. See https://github.com/jeremyrsmith/circe-yaml/pull/1 for an example of how to cause the tests to fail.

### PR DESCRIPTION
**Pull request by jeffmay**
@jeremyrsmith this adds all the necessary deprecations and quick fixes.

Changes in this branch:
- [x] Fix https://github.com/jeremyrsmith/circe-yaml/issues/2 in deprecated implementation
- [x] Deprecate the other printer / parser

Testing CI in this PR: https://github.com/jeffmay/circe-yaml/pull/1

### CODE REVIEW

**Comment by jeffmay** [comment]
@jeremyrsmith I'm not sure how to get my travis-ci account to hook up to your github account.

Would you want to set up an account? Alternatively, I don't mind hooking it up to my repo, but I think the CI would only work if we put PRs up against my fork, so we would have to update the link on circe's github.

**Comment by jeremyrsmith** [comment]
@jeffmay I'm happy to move this to another org; it can be yours if you like. As you probably noticed, I've got a bit much going on right now to work on circe-yaml.

I wonder how @travisbrown would feel about adopting it under `io.circe`? It's a bit orthagonal to circe's main goals, but otherwise (to me) would make sense as a circe module considering all it really aims to do is provide another JSON parser (which happens to also parse YAML).

I merged your PR for 0.3.0 which obviates these changes; so I'm going to go ahead and close this PR if that's OK with you. The reason is that it's really necessary to go through with updating cats and circe, and removing `Xor`. (Or I think it is necessary, since [finch](https://github.com/finagle/finch) no longer has any 0.11 version that supports a cats with `Xor`)

**Comment by jeffmay** [comment]
Yea, I mostly put these changes up to provide an easier migration path for anyone using 0.2.x, but I guess not too many people are using it?

I'm down to help maintain circe-yaml where ever it lives. Of course, I would be happy to add this to the main circe project as a module, if @travisbrown thinks its a good idea.

My only reason for changing the org is so I could hook it up to a CI pipeline. I think this is important, no matter where it lives. If you are busy, I'm happy to hook it up for you, but I would have to move it to another org. I'm volunteering https://github.com/gloriousfutureio which is a group that has a slack channel and a couple Scala devs, including myself. I will add a contributors section and mention everyone who contributes to the project.

The easiest way I can think of would be to transfer ownership to gloriousfutureio (after I delete the one I created: https://github.com/gloriousfutureio/circe-yaml), so that people's links are updated to go to the community edition. Also, I've seen main repos that are forks of someone's personal project, and it is hard to tell which one is the correct one to pull from, so it would help cut down on confusion. But again, this is more of an alternative to moving into circe itself.

**Comment by travisbrown** [comment]
I'd be happy to have this live in the circe repo proper, but it's getting kind of crowded and it probably makes sense to set up a circe organization. For what it's worth I just filed a request on for the inactive circe username, but we could also use circeio or circe-io if that doesn't work out.

**Comment by jeffmay** [comment]
Ok, @travisbrown, I'm down for a circe organization. I think that would make it easier to manage collaborators than using a single user. In the meantime, I can wait to add CI. If you decide it's too much trouble to make the org, I can put the PR up to circe.

Thanks!

**Comment by travisbrown** [comment]
Okay, GitHub has kindly freed up https://github.com/circe, and I'll be moving the main repo over there this evening. Should we move this project as well?

**Pull request closed without merging**
